### ISSUE TITLE
 module is not defined after updating to 2.9.0

### ISSUE THREAD

**Issue by mattiLeBlanc** [rzymek/meteor-moment#6]
Running 2.9.0 which pulls Moment 2.11.0.

I am seeing a module not defined error after updating:
![image](https://cloud.githubusercontent.com/assets/5285035/12077027/64744396-b21d-11e5-8285-103948c4d0ee.png)

or moment updated which changed how the locales are loaded?

I was specifically setting the locale:
moment.locale('en-AU')

However, I notice that when I do not use that line of code (the error disappears of course ) that the locale is en-au anyway.
(was there a case change?)

**Comment by tsega** [comment]
Yep it looks like it is a **case change** take a  [look at the code](https://github.com/moment/moment/blob/94ad539f965689289af54b6493abca0a65ab4ce6/locale/en-au.js#L13).

**Comment by mattiLeBlanc** [comment]
okay thanks.
