### ISSUE TITLE
Locale not applying

### ISSUE THREAD

**Issue by aleritty** [rzymek/meteor-moment#7]
Hi!

This is the repo: https://github.com/aleritty/event-manager

As you can see in `.meteor/packages` I'm using:
```
momentjs:moment
rzymek:moment-locale-it
mrt:moment-timezone
```

But in my pages code the locale remains en.

I also tried to set the locale in `/lib/environment.js:9` with no success.

If I try in the javascript console to set the locale:

```
> moment.locale();
"en"
> moment.locale('it');
"en"
> moment.locale();
"en"
```

Nothing works, I cannot tell if is an issue of the package or maybe a load order trouble.

**Comment by rzymek** [comment]
Does it work without `mrt:moment-timezone`?

**Comment by aleritty** [comment]
Damn, I didn't noticed that `mrt:moment-timezone` pulled `mrt:moment` loaded AFTER momentjs.

My fault! Sorry!
