### ISSUE TITLE
How to add a new locale `am`?

### ISSUE THREAD

**Issue by tsega** [rzymek/meteor-moment#8]
How can I add a new locale for the Amharic language (`am`)?

**Comment by rzymek** [comment]
I've updated the package to momentjs 2.12.0.
If there's still no locale you need then you need to consult the [momentjs docs](http://momentjs.com/docs/#/i18n/) or maybe do a pull request to [momentjs](https://github.com/moment/moment/)

**Comment by tsega** [comment]
Excellent, I am already in contact with the momentjs people and I just finished changing the labels to Amharic. I would be very happy to contribute both to momentjs and your package. Great work BTW!

**Just a thought to run by you**, we use a completely different calendar system; we have 13 months, today is 05-08-2008 (DD-MM-YYYY) :confused: :smile: . It would be great if you could point me to any resource that you know of that would help me get started with adding the [Ethiopian calendar system](https://en.wikipedia.org/wiki/Ethiopian_calendar) to moment.
